/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rxjava;

import io.reactivex.Observable;
import io.reactivex.disposables.Disposable;

public class App {

    public static void main(String[] args) {

        PriceOracle oracle = new PriceOracle();

        Observable<Double> prices = oracle.getPrices().getObservable();

        // Connect first observer
        Disposable d1 = prices.subscribe(item -> System.out.println("Ob 1: " + item));

        pause(2000);

        d1.dispose();
        oracle.kill();
    }

    private static void pause(int duration) {
        try {
            Thread.sleep(duration);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
